export const linksData = [
    {
        id:0,
        name: "Reddit",
        url: "https://wwww.reddit.com/",
        points: 20,
        upvoted: false,
        downvoted: false,
    },
    {
        id:1,
        name: "Twitch",
        url: "https://wwww.twitch.tv/",
        points: 15,
        upvoted: false,
        downvoted: false,
    },
    {
        id:2,
        name: "Youtube",
        url: "https://wwww.youtube.com/",
        points: 36,
        upvoted: false,
        downvoted: false,
    },
    {
        id:3,
        name: "Amazon",
        url: "https://wwww.amazon.com/",
        points: 18,
        upvoted: false,
        downvoted: false,
    },
    {
        id:4,
        name: "Stack Overflow",
        url: "https://wwww.stackoverflow.com/",
        points: 16,
        upvoted: false,
        downvoted: false,
    },
    {
        id:5,
        name: "Netflix",
        url: "https://wwww.netflix.com/",
        points: 45,
        upvoted: false,
        downvoted: false,
    },
    {
        id:6,
        name: "Product Hunt",
        url: "https://wwww.producthunt.com/",
        points: 20,
        upvoted: false,
        downvoted: false,
    },
];